/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatArea: typeof import('./src/components/ChatArea.vue')['default']
    ChatContainer: typeof import('./src/components/ChatContainer.vue')['default']
    ChatHeader: typeof import('./src/components/ChatHeader.vue')['default']
    ChatList: typeof import('./src/components/ChatList.vue')['default']
    Credits: typeof import('./src/components/Credits.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Notifier: typeof import('./src/components/Notifier.vue')['default']
    Request: typeof import('./src/components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SearchContact: typeof import('./src/components/SearchContact.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    UserHeader: typeof import('./src/components/UserHeader.vue')['default']
  }
}
