/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppContainer: typeof import('./components/AppContainer.vue')['default']
    ChatArea: typeof import('./components/ChatArea.vue')['default']
    ChatContainer: typeof import('./components/ChatContainer.vue')['default']
    ChatHeader: typeof import('./components/ChatHeader.vue')['default']
    ChatList: typeof import('./components/ChatList.vue')['default']
    Credits: typeof import('./components/Credits.vue')['default']
    MessageInput: typeof import('./components/MessageInput.vue')['default']
    MessageUpload: typeof import('./components/MessageUpload.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    Request: typeof import('./components/Request.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchContact: typeof import('./components/SearchContact.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Sse: typeof import('./components/Sse.vue')['default']
    UserHeader: typeof import('./components/UserHeader.vue')['default']
  }
}
